// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCpVIqBTvd6Q1C4weysTtm-07P6dmy0c',
    appId: '1:870317025836:web:05d1c73fa9272edd03bf89',
    messagingSenderId: '870317025836',
    projectId: 'dreamstar-1d71c',
    authDomain: 'dreamstar-1d71c.firebaseapp.com',
    storageBucket: 'dreamstar-1d71c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDElQP0rzRIa6395oR46zYinFKVHcLufmE',
    appId: '1:870317025836:android:af25906e537adec303bf89',
    messagingSenderId: '870317025836',
    projectId: 'dreamstar-1d71c',
    storageBucket: 'dreamstar-1d71c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJGLCQrkkEf77nehfBuhomnnXJ92HXr-s',
    appId: '1:870317025836:ios:43ae6350e75889ad03bf89',
    messagingSenderId: '870317025836',
    projectId: 'dreamstar-1d71c',
    storageBucket: 'dreamstar-1d71c.appspot.com',
    iosClientId:
        '870317025836-racnhao9qptfenjnp2tamsa1ul051uql.apps.googleusercontent.com',
    iosBundleId: 'dev.dada.dreamStar',
  );
}
